# Azure Static Web Apps deployment configuration
# This file should be placed in .github/workflows/ directory

name: Deploy Outlook Add-in to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: |
        # Create a simple build process for static files
        mkdir -p dist
        cp -r *.html *.css *.js *.xml assets dist/
        cp -r dataverse-service.js sharepoint-service.js dist/
        
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        output_location: "dist"
        skip_app_build: true
